### ISSUE TITLE
chore: can it index litecoin/dogecoin?

### ISSUE THREAD

**Issue by davidp94** [haskoin/haskoin-store#28]
@jprupp does this project be able to support litecoin/dogecoin?

If yes - is there any instructions?
If not - what is the blocking point?

**Comment by jprupp** [comment]
If you understand how Dogecoin or Litecoin works, and you are a competent Haskell developer, you should look at the code in [Haskoin Core](/haskoin/haskoin-core), do the required changes in a branch of your own, and submit a pull request. You should commit to maintain such code for future hard or soft forks. Since both Litecoin and Dogecoin are not extremely different from Bitcoin, I don't think it would be extremely difficult to support either.
